MyCompany/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCompany.Models;
using MyCompany.Serveces.Interfaces;

namespace MyCompany.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICourses _courses;

        public CoursesController(ICourses courses)
        {
            _courses = courses;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _courses.AllCourses());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            ViewBag.CourseID = id;

            return View(await _courses.Details(id));
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseID,CourseName")] Course course)
        {
            if (ModelState.IsValid)
            {

                if (await _courses.Create(course))
                {
                    return Redirect($"/Courses/Details/{course.CourseID}");
                }
                else
                {
                    return NotFound();
                }
                //return RedirectToAction(nameof(Index));
            }

            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            return View(await _courses.Edit(id));
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CourseID,CourseName")] Course course)
        {
            if (ModelState.IsValid)
            {
                if (await _courses.TryEdit(id, course))
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                }
            }

            return View(course);
//Exception thrown by DbContext when it was expected that SaveChanges for an entity would result in a database update but
//in fact no rows in the database were affected. This usually indicates that the database has been concurrently updated
//such that a concurrency token that was expected to match did not actually match. Note that state entries referenced by
//this exception are not serialized due to security and accesses to the state entries after serialization will return null.
// https://docs.microsoft.com/ru-ru/ef/core/saving/concurrency
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            return View(await _courses.Delete(id));
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (await _courses.DeleteConfirmed(id))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("CourseName", "Невозможно удалить курс т.к. в нём содержатся группы");
                return View(_courses.GetCourse(id));
            }

        }
    }
}

MyCompany/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCompany.Models;
using MyCompany.Serveces.Interfaces;

namespace MyCompany.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IGroups _groups;

        public GroupsController(IGroups groups)
        {
            _groups = groups;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            return View(await _groups.AllGroups());
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            ViewBag.GroupID = id;

            return View(await _groups.Details(id));
        }

        // GET: Groups/Create
        public IActionResult Create(Guid id)
        {
            ViewBag.CourseID = id;

            return View(_groups.GetNewGroup(id));
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupID,CourseID,GroupName")] Group @group)
        {
            if (ModelState.IsValid)
            {
                await _groups.Create(@group);
                return Redirect($"/Groups/Details/{group.GroupID}");
            }

            return View(@group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            return View(await _groups.Edit(id));
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("GroupID,CourseID,GroupName")] Group @group)
        {
            if (ModelState.IsValid)
            {
                if (await _groups.Edit(id, @group))
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                }
            }
            return View(@group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {

            return View(await _groups.Delete(id));
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var group = await _groups.GetGroup(id);
            
            if (await _groups.DeleteConfirmed(id))
            {
                return Redirect($"/Courses/Details/{group.CourseID}");
            }
            else
            {
                ModelState.AddModelError("GroupName", "Невозможно удалить группу т.к. в ней содержатся студенты");
                return View(group);
            }
            

            //return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(Guid id)
        {
            return _groups.GroupExists(id);
        }
    }
}

MyCompany/Views/Courses/Create.cshtml
@model MyCompany.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить курс</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control" required/>
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MyCompany/Views/Courses/Delete.cshtml
@model MyCompany.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Вы уверены что хотите удалить курс "@Model.CourseName"</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="CourseID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
    <span asp-validation-for="CourseName" class="text-danger"></span>
</div>

MyCompany/Views/Courses/Details.cshtml
@model IEnumerable<MyCompany.Models.Group>

@{
    ViewData["Title"] = "Details";
}

<h1>Список групп</h1>
<div>
    <a asp-action="Create" asp-controller="Groups" asp-route-id="@ViewBag.CourseID">Добавить группу</a>
</div>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GroupName)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupName)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="Groups" asp-route-id="@item.GroupID">Edit</a> |
                        <a asp-action="Details" asp-controller="Groups" asp-route-id="@item.GroupID">Details</a> |
                        <a asp-action="Delete" asp-controller="Groups" asp-route-id="@item.GroupID">Delete</a> |
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MyCompany/Views/Courses/Edit.cshtml
@model MyCompany.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CourseID" />
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyCompany/Views/Courses/Index.cshtml
@model IEnumerable<MyCompany.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1>Список курсов</h1>

<p>
    <a asp-action="Create">Добавить курс</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CourseID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CourseID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CourseID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MyCompany/Views/Courses/View.cshtml
@{
    ViewData["Title"] = "View";
}

<h1>View</h1>