MyCompany/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyCompany.Models
{
    public class Group
    {
        public Guid GroupID { get; set; }
        public Guid CourseID { get; set; }

        [Required (ErrorMessage = "Необходимо ввести название группы")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "Недопустимая длинна")]
        [RegularExpression(@"\S+", ErrorMessage = "Недопустимое название для данного поля")]
        [Display(Name = "Название группы")]
        public string GroupName { get; set; }
        public List<Student> Students { get; set; } = new List<Student>();

    }
}

MyCompany/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCompany.Models;
using MyCompany.Serveces.Interfaces;

namespace MyCompany.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IGroups _groups;

        public GroupsController(IGroups groups)
        {
            _groups = groups;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            return View(await _groups.AllGroups());
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            ViewBag.GroupID = id;

            return View(await _groups.Details(id));
        }

        // GET: Groups/Create
        public IActionResult Create(Guid id)
        {
            ViewBag.CourseID = id;

            return View(_groups.GetNewGroup(id));
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupID,CourseID,GroupName")] Group @group)
        {
            if (ModelState.IsValid)
            {
                await _groups.Create(@group);
                return Redirect($"/Groups/Details/{group.GroupID}");
            }

            return View(@group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            return View(await _groups.Edit(id));
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("GroupID,CourseID,GroupName")] Group @group)
        {
            if (ModelState.IsValid)
            {
                if (await _groups.Edit(id, @group))
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                }
            }
            return View(@group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {

            return View(await _groups.Delete(id));
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var group = await _groups.GetGroup(id);
            
            if (await _groups.DeleteConfirmed(id))
            {
                return Redirect($"/Courses/Details/{group.CourseID}");
            }
            else
            {
                ModelState.AddModelError("GroupName", "Невозможно удалить группу т.к. в ней содержатся студенты");
                return View(group);
            }
            

            //return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(Guid id)
        {
            return _groups.GroupExists(id);
        }
    }
}

MyCompany/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCompany.Models;
using MyCompany.Serveces.Interfaces;

namespace MyCompany.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudents _students;

        public StudentsController(IStudents students)
        {
            _students = students;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            return View(await _students.GetAllStudents());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            ViewBag.GroupID = id;

            return View(await _students.Details(id));
        }

        // GET: Students/Create
        public IActionResult Create(Guid id)
        {
            ViewBag.GroupID = id;
            //Student newStudent = new Student()
            //{
            //    GroupID = id
            //};
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentID,GroupID,Name,Surname,Age")] Student student)
        {
            if (ModelState.IsValid)
            {
                await _students.Create(student);

                return Redirect($"/Groups/Details/{student.GroupID}");
                //return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            return View(await _students.Edit(id));
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("StudentID,GroupID,Name,Surname,Age")] Student student)
        {
            if (ModelState.IsValid)
            {
                if (_students.StudentExists(id))
                {
                    await _students.Edit(id, student);

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                }
                
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            return View(await _students.Delete(id));
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var student = await _students.FindStudent(id);
            await _students.DeleteConfirmed(id);

            return Redirect($"/Groups/Details/{student.GroupID}");
        }

        private bool StudentExists(Guid id)
        {
            return _students.StudentExists(id);
        }
    }
}

MyCompany/Views/Groups/Create.cshtml
@model MyCompany.Models.Group

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить группу</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="CourseID" class="control-label"></label>*@
                <input type="hidden" asp-for="CourseID" />
                @*<select asp-for="CourseID" class="form-control" asp-items="@Model.CourseID" required></select>*@
            </div>
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" required />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MyCompany/Views/Groups/Delete.cshtml
@model MyCompany.Models.Group

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="GroupID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
    <span asp-validation-for="GroupName" class="text-danger"></span>
</div>

MyCompany/Views/Groups/Details.cshtml
@model IEnumerable<MyCompany.Models.Student>

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <a asp-action="Create" asp-controller="Students" asp-route-id="@ViewBag.GroupID">Добавить студента</a>
</div>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="Students" asp-route-id="@item.StudentID">Edit</a> |
                        <a asp-action="Details" asp-controller="Students" asp-route-id="@item.StudentID">Details</a> |
                        <a asp-action="Delete" asp-controller="Students" asp-route-id="@item.StudentID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MyCompany/Views/Groups/Edit.cshtml
@model MyCompany.Models.Group

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GroupID" />
            <input type="hidden" asp-for="CourseID" />
            @*<div class="form-group">
                    <label asp-for="CourseID" class="control-label"></label>
                    <select asp-for="CourseID" class="form-control" asp-items="ViewBag.CourseID"></select>
                    <span asp-validation-for="CourseID" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyCompany/Views/Groups/Index.cshtml
@model IEnumerable<MyCompany.Models.Group>

@{
    ViewData["Title"] = "Index";
}

<h1>Список групп</h1>

@*<p>
    <a asp-action="Create">Добавить группу</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.GroupID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.GroupID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.GroupID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>